var GAME_LEVELS = [
  ["                                                                                ",
   " !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "                           v                    v             v                 ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                            xx  ",
   "  xx                                                                         x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                               o o        x  ",
   "  x  @          o                     o                   o      xxxxx       x  ",
   "  xxxxxxx       x      x      x       x      x      x     x                  x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                 xxx                                                              ",
   "                                                 x!x                                                              ",
   "                                                 x!x                                                              ",
   "                                                 x!x                                                              ",
   "                                                 xvx                                                              ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                               x     x                           xxx         xxx                  ",
   "                                               x    xx                           x x         x x                  ",
   "                                     xx        x=    x                             x         x                    ",
   "                                              xx     x                             x         x                    ",
   "                                               xx    x                           o x         x                    ",
   "=                                              x     x      o  o     xxxxxxxxxxxxxxx         x                    ",
   "               xxxxxxx        xxx!!!xxx        x     x               x v x!!!!!!!!!x         x                    ",
   "              xx     xx         x!!!x          x     x     xxxxxx    x   x!!!xxxxxxx         x                    ",
   "             xx       xx        x!!!x         xx    xx               x   x!!!x               x                    ",
   "     @       x         x        x!!!x          x     x               x   xxxxx               x                    ",
   "    xxx      x         x        x!!!x     o    x     x               x                       x                    ",
   "    x x      x         x       xx!!!xx    ?    x     x               x                       x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!x         =                  x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xxv            xxxxxx xx       xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx         o            xx o o xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                   xxxx!!!!!!xx?         x             xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxxxxxxxxxxxx!!!!!!!!!xxxxxxxxxx                                              ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx  ",
   "  x x         v                   v                  v                    v          v         v         x x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x           =                                              =                                  =      ????x  ",
   "  x                          o      =                                                             o        x  ",
   "  x                o     x   x         o   =               x      xxxx   xxx x   x     x    x     x        x  ",
   "  x                x              x    x     x     ?   x                                                   x  ",
   "  x      @     x      =                         =                =                                         x  ",
   "  xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                  ?    ? ????? ?   ?      ?   ?   ? ? ?????? ?                                                ",
   "                  ?    ? ?   ? ?   ?      ?   ?   ?   ?    ? ?                                                ",
   "                  ?????? ?   ? ?   ?      ?   ?   ? ? ?    ? ?                                                ",
   "                    ??   ?   ? ?   ?      ?   ?   ? ? ?    ?                                                  ",
   "                    ??   ????? ?????      ????????? ? ?    ? ?                                                ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x  @                                                                                                        ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
